"""composite index added

Revision ID: 189e3df8ad8c
Revises: 0e3854c6c16b
Create Date: 2026-09-19 08:32:40.346169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189e3df8ad8c'
down_revision: Union[str, Sequence[str], None] = '0e3854c6c16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_user_created', 'tasks', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_user_created', table_name='tasks')
    # ### end Alembic commands ###
